/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Sun Jul 31 2016 22:44:57 GMT-0300 (BRT)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */

import { AppEnv } from './env.model';

export const ENV: AppEnv = {
};
